### ISSUE TITLE
Memory leak when outputting to another file format

### ISSUE THREAD

**Issue by melvinroest** [CLARIAH/COW#106]
**Observed**
I was auditing the code for CoW and thought to have spotted a memory leak when the file format is *not* nquads (so everything else). 

**Implications**
For big csv files such a memory leak means that CoW gets killed when it needs to output to that file. Note: in this particular bug, it does mean that the conversion is still saved to `.nq`. So while the data isn't lost, it can never be outputted to another file format that is not `.nq`, even if you specified that it should be outputted to another format.

**Desired behavior**
What I wanted CoW to do was to output it to the specified file format. In my specific test this was the `trig` format.

**How to reproduce**
I took a big dataset of around 3.5GB that I can't share here, but that's what I used. But you can make an arbitrary CSV file of 3.5GB yourself of fake data. I recommend to have at least 10 to 20 columns and then run the following:
* `cow_tool build fakedata.csv`
* `cow_tool convert fakedata.csv --format trig`

**Evidence**
In this particular screenshot I ran the command `python3 src/csvw_tool.py convert my_very_big_file.csv --processes 10 --format trig`

I modded my version for CoW to notify me when it was trying to output to the `trig` format. When you look at the memory usage and swap usage, it's almost maxing out and my operating system killed the CoW. 

Under normal circumstances my system was nowhere near maxing out (7.5GB RAM and no swap used).
![image](https://user-images.githubusercontent.com/44729293/99162710-e9260b80-2700-11eb-89ca-66569c0da7cf.png)

**The offending code**
Since this was an audit and I was correct after testing, I suspect that the following code is producing the bug:

```
#csvw_tool.py
if output_format not in ['nquads']:
    with open(source_file + '.' + 'nq', 'rb') as nquads_file:
        g = ConjunctiveGraph()
        g.parse(nquads_file, format='nquads')
```

In particular, `g.parse(nquads_file, format='nquads')` is hogging up all the memory.

**Comment by wxwilcke** [comment]
Hi @melvinroest,

Thank you for reporting this.
The code in question makes use of the RDFlib library which needs to loads the current graph into memory before it is able to convert it to another serialization format, which also happens in memory. In other words, this required both graphs to be in memory, which, for a 3.5G file plus overhead, will indeed kill your system.

I'm closing this since this isn't a memory leak and since remedying this would require a different Python library that can read and write RDF in different formats (which doesn't exist as far as I know). If you really feel this is an issue, then the only solution would be to remove this option, and let user use a different tool if they need to convert the output (eg Raptor [1])

Best,
Xander

[1]https://librdf.org/raptor/rapper.html
