### ISSUE TITLE
line options

### ISSUE THREAD

**Issue by rlzijdeman** [CLARIAH/COW#19]
Hi, to assess whether you're converting a file properly, usually you just take a sample of the file. It would be great if one could specify a line range to be read in from the .csv file. This would have having to create sample files and in case of errors allows more quickly to see whether it is related to the .csv file itself. I'm thinking something like:

`python csvw-tool.py convert -l 5:100 myFile.csv` line 5-100
`python csvw-tool.py convert -l +100 myFile.csv` first 100 lines
`python csvw-tool.py convert -l -100 myFile.csv` last 100 lines

**Comment by rlzijdeman** [comment]
removed wontfix label... for very big files it is imperative to  use this feature

**Comment by melvinroest** [comment]
I don't think this feature is needed. I googled for it by typing "command line extract different lines from file" and clicked around a bit and found the following to work.

```
sed -n '2,4p; 6,8p;' temp.txt > mycsv.csv
````

This extracts lines 2 to 4 and 6 to 8. You need the `p` because it stand for **p**rint. And the `;` is needed because your giving multiple commands (two commands, one for 2 to 4 and one for 6 to 8).
