### ISSUE TITLE
@base doesn't seem to be parsed anymore

### ISSUE THREAD

**Issue by rlzijdeman** [CLARIAH/COW#22]
So to sum the issue based on the discussion on datalegend's Slack:

the issue at hand appears to lie in the fact that the base url defined in @base is not parsed as part of the aboutUrl when using COW to convert;
- manually overriding the baseUrl with "" in the prefix specification does not alter this;
- using a combination of a prefix with {_row} does not work either (e.g. hsn:{_row});
- a quick fix is to explicate the baseUrl like so: "aboutUrl": "http://example.org/resource/{_row}",

**Comment by albertmeronyo** [comment]
So I've had a close look at this.

The root of the problem is not in COW's code, but in the [JSON-LD parser of rdflib](https://github.com/RDFLib/rdflib-jsonld). As described [here](http://csvw-converter.readthedocs.io/en/latest/), COW expects the JSON-LD parser to read the @base value in the @context of the JSON file and use that as namespace for aboutUrl. That's just not happening anymore, probably because of latest changes in rdflib, rdflib-jsonld, or both (will look this further). As a result, instead of patterns of the form

```
http://example.com/{_row}/{{Country}}
```

The iribaker is getting

```
{_row}/{{Country}}
```

Which obviously fails to parse. The next commit patches this by always adding the base before aboutUrl while generating the default JSON file.

**Comment by rlzijdeman** [comment]
Hi @albertmeronyo, I'm afraid the prefixes are still problematic. E.g. using the example file (imf_gdppc.csv) and adding

**Comment by albertmeronyo** [comment]
Did this

```
"propertyUrl": "rdf:type"
```

ever work before we started having issues? I understood yesterday from @rijpma that namespace expansion was never supported (but maybe I got this wrong).

**Comment by rlzijdeman** [comment]
yes... e.g. in the sdh-private-hisco you'll find occupation_link.csv-metadata.json containing:
```
            {
                "datatype": "string",
                "titles": [
                    "country_code"
                ],
                "name": "country_code",
                "dc:description": "The country code (non-standard)",
                "propertyUrl": "sdmx-dimension:refArea",
                "valueUrl": "{{country_code|lower}}"
            },
```
which results in the occupation_link.csv.nq file, for example, in:

```
<http://data.socialhistory.org/resource/hisco/LNP/zingueur> <http://purl.org/linked-data/sdmx/2009/dimension#refArea> <http://data.socialhistory.org/resource/hisco/bel> 
```

**Comment by albertmeronyo** [comment]
Great! Thanks for the example. Looking into it

**Comment by albertmeronyo** [comment]
See RDFLib/rdflib-jsonld#48

**Comment by albertmeronyo** [comment]
So after thorough investigation and thanks to the guys at rdflib-jsonld, it all comes down to a new JSON-LD context by the CSVW WG of the W3C. Basically the new version changes the schema types for aboutUrl, propertyUrl and valueUrl (where we use our fancy patterns), from @id to csvw:uriTemplate. This breaks both auto-prepending @base, expanding namespaces, and expanding patterns (so issues #22 and #23).

There are two possible fixes: adapting COW to the new standard, or minting our own context. The former is  expensive (since a lot of work that the JSON-LD parser did for us needs to be coded into COW), and possibly unworthy since we were already standard non-compliant. The last commit implements the latter, which is simply a new JSON context we need to use in our schema files instead of https://www.w3.org/ns/csvw. The context to use from now on is http://csvw.clariah-sdh.eculture.labs.vu.nl/csvw.json (probably we'll want to move this to a stable IISG host).

New schema files will be generated according to this, but old ones will need to be fixed. So we'll need to gather a list of all JSON schema files we have and run some regexp replace.
