### ISSUE TITLE
inconsistent base URI application?

### ISSUE THREAD

**Issue by rijpma** [CLARIAH/COW#32]
Having just tried the latest version of COW, with build and convert on the test file (imf_gdppc.csv) without any edits to the metadata json-file, we (@morkor and me) get what seems to to us inconsistent URIs across sub/pred/graph

`<https://iisg.amsterdam/resource/6> <http://data.socialhistory.org/resource/Int> "72,524"^^<http://www.w3.org/2001/XMLSchema#string> <http://iisg.amsterdam/imf_gdppc/assertion/0f8040d8/2017-11-01T14:45> .`

Note the difference between subject (iisg.amsterdam/resource/) and predicate (data.socialhistory.org). I think this happens here:

https://github.com/CLARIAH/COW/blob/b95bb3027ef6471547b3d86a1ca4831e0f6259f2/src/converter/csvw.py#L510

But don't feel confident to start changing the converter's internals. I'm also having trouble finding the base  in BurstConverter, which would the best thing to replace data.socialhistory.org with IMO.

The other thing is that the graph predicate does not have the /resource/ bit. I can see how this would be on purpose, but just wanted to make sure this is what we want. Either way, the fact that /resource/ is missing means that it is not based on the base-URI in the metadatafile, but hardcoded somewhere else in the converter which limits its usability for people who are not iisg.amsterdam.

**Comment by rlzijdeman** [comment]
Hi, well spotted: to illustrate, if you run `cow_tool build imf_gdppc.csv  --base "http://uu.nl/seh"` 

you'll get

`<http://uu.nl/seh/6> <http://data.socialhistory.org/resource/Int> "72,524"^^<http://www.w3.org/2001/XMLSchema#string> <http://iisg.amsterdam/imf_gdppc/assertion/0f8040d8/2017-11-01T15:19> .`

**Comment by albertmeronyo** [comment]
Thanks @rijpma and @rlzijdeman 
I have been looking at this, but this inconsistency might actually be a feature and not a bug. It's considered good practice to have two different prefixes separating dataset resources and vocabulary terms; so you typically have

```
@prefix foo-r : <http://foo.baz/resource/>
@prefix foo: <http://foo.baz/vocab#>
```

And then you find them in the data as

`<http://foo.baz/resource/1> <http://foo.baz/vocab#myProperty> "value" .`

Another question would be whether we want to allow users to mint their own vocabulary dataspaces instead of defaulting to ours, so adding a parameter like this would allow that:

<pre>
$ cow_tool build myfile.csv --base=http://foo.baz/resource/ <b>--vocab=http://foo.baz/vocab#</b>`
</pre>

Would that make sense?

**Comment by rlzijdeman** [comment]
Hi @albertmeronyo,

ok, that makes sense. But that still leaves these issues:

1. without specifiying --base  `resource/` is added to the base-uri and that should not be the case. (note that if you build the file, the @base in the .json file is `https://iisg.amsterdam/resource` and should be `https://iisg.amsterdam`

1. the default uri for the property should start with `https://iisg.amsterdam` as well, rather than `http://data.socialhistory.org`. The vocab parameter you suggest, would indeed be an important addition.

1. some of these uri's (http://data.socialhistory.org) are hard-coded in COW.

I have created the [cbase](https://github.com/CLARIAH/COW/tree/cbase) branch to resolve the latter. Hope that helps.

**Comment by rijpma** [comment]
All good suggestions, agree that distinguishing between vocab and data is a good idea. Just to make sure we are talking about the same rules, I'm putting the four outcomes below. 

Nothing specified, all defaults: `cow_tool build myfile.csv `:

```<http://data.iisg.amsterdam/resource/1> <http://data.iisg.amsterdam/vocab#myProperty> "value" .```

---

All specified, no defaults: `cow_tool build myfile.csv --base=http://foo.baz/resource/ --vocab=http://foo.baz/vocab#`:

```<http://foo.baz/resource/1> <http://foo.baz/vocab#myProperty> "value" .```

---

Base specified, vocab default: `cow_tool build myfile.csv --base=http://foo.baz/resource/`:

```<http://foo.baz/resource/1> <http://data.iisg.amsterdam/vocab#myProperty> "value" .```

---

And vocab specified, base default: `cow_tool build myfile.csv --vocab=http://foo.baz/vocab#`:

```<http://data.iisg.amsterdam/resource/1> <http://foo.baz/vocab#myProperty> "value" .```

---

And in all this the base for the object is the same as the subject.

Only alternatives to this that I see are (i) not allowing specifying only one of the two, i.e. specify none or both; (ii) inferring vocab from base or the other way around. Latter seems a lot of trouble for something that is not that much to ask from the user.

**Comment by rlzijdeman** [comment]
Thanks @rijpma . I like the logic, just changed the uri (`https` rather than `http` and `filename_without_extension` rather than `/resource`. Would you agree?

**Comment by rijpma** [comment]
Agreed of course on the http/https, just me being sloppy there. 

I would say `resource/filename_without_extension` and `vocab` without the further specification (as these should be shared when possible). Adding the further specification to the default is important because it we do not use it, the default behaviour is to have shared subject names across datasets, while they would usually not refer to the same entity. 

One might argue that the default can include the extension -- if you want a sensible name, you'd probably specify the base. If you don't specify the base, including the extention lowers the prob of a prefix clash because people give their files stupid names like "data".

**Comment by albertmeronyo** [comment]
Change list:
- Change default base to ``https://iisg.amsterdam/<filename>``
- Add warning that you did not specify default base URI, using the one in the previous bullet
- Change default propertyUrl to ``https://iisg.amsterdam/<c.csvw_name>``
- Default propertyUrl's should take the form of ``<base>/vocab/<COLUMN_NAME>``
