### ISSUE TITLE
duplicate files in cow-folder and src-folder

### ISSUE THREAD

**Issue by RoderickvanderWeerdt** [CLARIAH/COW#60]
The cow-folder seems to be a duplicate of the src-folder, containing (almost) the same files. Unfortunately both folder have had changes since, they were created so the contents of both of the folders need to compared to see what needs to remain.

**Comment by rijpma** [comment]
Hi Roderick,

(Sorry for the late response, ignore if you already figured this out).

From the what I know, the data people stopped using the version in the src-folder and are now using the one in the cow-folder for conversions. I think the src-folder version should be removed to prevent confusion.

I think the changes that have been applied to the src-folder since that moment are the following

https://github.com/CLARIAH/COW/commit/1825c6eb52232efb161d533a0f5c6469da8a296d#diff-253ff3cb7dc7c408042463b59552336c (fix of issue 32)

https://github.com/CLARIAH/COW/commit/03e2a601f651fa8520f4c65312779ee8436c1cc2#diff-d1a7484615fce7ccc2f07de8f035ea4b (Albert's branch merge, not sure what was merged and what it was supposed to do)

https://github.com/CLARIAH/COW/commit/5b6afb6f72d70fbddfac769639379a92577f8d5f#diff-253ff3cb7dc7c408042463b59552336c (linux/macos/windows path handling, not applied to cow-folder)

https://github.com/CLARIAH/COW/commit/80ac344a8ddc5e9f1ed73103d3213c785c8a692c (Richard's http https namespace fix for iisg.amsterdam, not fully applied to cow-folder yet).

Let me know if I can help out.

Auke

**Comment by RoderickvanderWeerdt** [comment]
I agree, and that's what I did, with the exception of keeping the src-folder instead and removing the cow-folder.
