### ISSUE TITLE
aboutUrl not working in column definitions

### ISSUE THREAD

**Issue by tkuhn** [CLARIAH/COW#83]
A line like

    "aboutUrl": "http://example.org/foobar/"

in the column definitions doesn't seem to have an effect. It should, if I understand the spec correctly, allow me to specify the subject of the triples that are generated for the given column.

**Comment by melvinroest** [comment]
@tkuhn: the use of an `aboutUrl` like that means you'll generate (if it'd work) the same subject for all rows. Is that what you were going for, or was there another reason why there's a string literal there?

In all the `aboutUrl` examples, there is always some form of curly brackets enclosing (`{ }`).

**Comment by rlzijdeman** [comment]
Hi, sorry for the late reply @tkuhn 

Setting the aboutUrl to something different than the baseUrl, requires the specification of a virtual column.

please see (default aboutUrl):
https://github.com/CLARIAH/COW/wiki/05.-setting-the-aboutUrl-(subject)

and (new aboutUrl):
https://github.com/CLARIAH/COW/wiki/08.-adding-data:-virtual-columns

If this doesn't work, please show me a minimal example. It could be due to the Python  2.7 / 3.x conversion issue. I can confirm that aboutUrl's work normally in 2.7

**Comment by tkuhn** [comment]
Using a virtual column did the trick. Thanks!
